# Generated by Django 5.0.2 on 2024-03-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_attendance_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
