# Generated by Django 5.0.2 on 2024-03-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_attendance_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='area',
        ),
        migrations.RemoveField(
            model_name='member',
            name='NPA_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='area',
        ),
        migrations.RemoveField(
            model_name='member',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='day_to_be_visited',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='hop',
        ),
        migrations.RemoveField(
            model_name='member',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zone',
        ),
        migrations.AddField(
            model_name='member',
            name='perfect_attendance',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
