# Generated by Django 5.0.2 on 2024-03-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_attendance_area_remove_member_npa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalattendancecount',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.attendance'),
        ),
    ]
